# Generated by Django 4.2.6 on 2023-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
